### ISSUE TITLE
Commit changes to SubPageList back to main project

### ISSUE THREAD

**Issue by emanspeaks** [FodWikis/FodWikis#12]
I made some tweaks to the SubPageList extension a while ago I intended to submit to the project when I figured out how to use Gerrit.  Now that I know how to do this, I'll get this done whenever I get a chance.  Wanted to create as an issue here so everyone knows TOPO is using a different version of SPL than everyone else.

**Comment by jamesmontalvo3** [comment]
SubPageList is actually written by a guy named [Jeroen De Dauw](https://github.com/JeroenDeDauw), who is one of the primary maintainers of [Semantic MediaWiki](https://github.com/SemanticMediaWiki/SemanticMediaWiki). While most MediaWiki extensions are housed on WMF servers, SMW does all of its development on GitHub. As such, so does Jeroen (who I think drove them to GitHub). Lovely, right? So you can find SubPageList at: https://github.com/JeroenDeDauw/SubPageList

**Comment by emanspeaks** [comment]
Well, that's good news.  

It's adding functionality, not changing any existing functionality IIRC (I did it quite a while ago now).  We should push this out to everyone as part of our effort to reconcile all the different configs.

**Comment by jamesmontalvo3** [comment]
Let me know when your version is on GitHub...I'd like to see the change.

**Comment by emanspeaks** [comment]
https://github.com/JeroenDeDauw/SubPageList/pull/9 is a link to my pull request with my changes.

**Comment by emanspeaks** [comment]
All my changes have been merged into master branch.  https://github.com/JeroenDeDauw/SubPageList is now at version 1.2 with my updates.

**Comment by jamesmontalvo3** [comment]
I pulled SubPageList 1.2 into all the dev wikis yesterday (when I realized TOPO dies without it).
