### ISSUE TITLE
Updated "NoApprovedRevs" style and words for TOPO

### ISSUE THREAD

**Issue by emanspeaks** [FodWikis/FodWikis#14]
Note: this is not the change I suggested in https://github.com/enterprisemediawiki/Meza1/issues/96

TOPO made a few small changes to ApprovedRevs to some of the text and formatting per direction from our Group Lead.  Minor changes listed here:

In ApprovedRevs.i18n.php:
'approvedrevs-noapprovedrevision' => 'This is the latest revision of this page; it is not currently in an approval workflow.',

In ApprovedRevs.hooks.php:

``` php
public static function displayNotApprovedHeader( Article &$article, &$outputDone, &$useParserCache ) {
        global $egApprovedRevsShowNotApprovedMessage;
        if ( !$egApprovedRevsShowNotApprovedMessage) {
            return true;
        }

        //rae edit
        ApprovedRevs::addCSS();
        $text = Xml::element(
            'span',
            array( 'class' => 'noApprovedRev' ),
            wfMsg( 'approvedrevs-noapprovedrevision' )
        );
        //end rae edit

        $title = $article->getTitle();
        if ( ! ApprovedRevs::hasApprovedRevision( $title ) ) {
            //$text = wfMessage( 'approvedrevs-noapprovedrevision' )->text();

            global $wgOut;
            if ( $wgOut->getSubtitle() != '' ) {
                $wgOut->appendSubtitle( '<br />' . $text );
            } else {
                $wgOut->setSubtitle( $text );
            }
        }

        return true;
    }
```

**Comment by emanspeaks** [comment]
tracking these changes in my personal ApprovedRevs repo on GitHub.

https://github.com/emanspeaks/ApprovedRevs/compare/master...add_noApproved_style

https://github.com/emanspeaks/ApprovedRevs/compare/master...TOPO_noApproved_words

**Comment by emanspeaks** [comment]
While it would be better long-term to add the changes I have in https://github.com/emanspeaks/ApprovedRevs/tree/add_noApproved_style , this has been remedied for now by including the span tag in my text in [[MediaWiki:Approvedrevs-noapprovedrevision]].

**Comment by jamesmontalvo3** [comment]
So does this mean TOPO is back on the same ApprovedRevs version as the other wikis?

**Comment by emanspeaks** [comment]
I have not reverted back my changes to the code, but yes we are back to using only the standard features for now.  We can go back to the common version anytime.

**Comment by jamesmontalvo3** [comment]
Great, that's one of my last open issues to having a standard config. When we're on FOD2 we'll have the common version for all.
