### ISSUE TITLE
Remove extra wikitable format from imported articles

### ISSUE THREAD

**Issue by olsonjaredm** [FodWikis/FodWikis#15]
Many pages seem to have been formatted during the import from sharepoint to mediawiki with a surrounding wikitable. We've been manually removing this when noticed, but a faster or more comprehensive solution would be welcome.

> {| class="wikitable"  cellspacing="2" cellpadding="2"
> |  |
> ....content....
> |}
> 
> false,false,1

![image](https://cloud.githubusercontent.com/assets/13458815/9046863/6d33137e-39f3-11e5-93ed-652c74d62518.png)

**Comment by jamesmontalvo3** [comment]
For the "false,false,1" thing you can use [[Special:ReplaceText]]. Just do a global find for "false,false,1" and replace with nothing.

Scripting the removal of the tables may be more difficult. You probably could use [[Special:ReplaceText]] to find `{| class="wikitable" cellspacing="2" cellpadding="2"`, but not actually do the replace. Then at least you'd have a list of pages you need to fix.

**Comment by jamesmontalvo3** [comment]
@mcmarti2 Nice!
