### ISSUE TITLE
Create SPARTAN/PRO Wiki

### ISSUE THREAD

**Issue by jamesmontalvo3** [FodWikis/FodWikis#21]
From Michael Way:

> Currently we have one Wiki that is being used to store “procedures” (for lack of a better term) that govern use of a software tool that we use for power analysis. So, it’s not exactly the same as one that would be used for systems knowledge capture. However, we don’t want to limit ourselves to just the software tool procedures. We were thinking that the content contained in this wiki would be a subset of the content.  

Import Sharepoint wiki content. See [standard-sharepoint-domain]/MOD/DI/DI4/PLATO/PLATO%20Users%20Guide/PLATO%20Operation%20Procedures.aspx

**Comment by darenwelsh** [comment]
SPARTAN wiki is now functioning. Michael Way is an admin and has been informed how to add users. I also asked him to join us on Slack.
