### ISSUE TITLE
Create Orion ODB Wiki

### ISSUE THREAD

**Issue by jamesmontalvo3** [FodWikis/FodWikis#22]
From Greg Smith:

> FOD has been tasked with helping Lockheed develop an Orion ODB, similar to the SODB (shuttle ops data book). The SODB consisted of several volumes and thousands of paper pages. We have different sections for each system (communications, GNC, Thermal ,etc) … kind of like how you categorize EVA Tools. Darrin and I would like to prototype a page with some system some content (sample format below) to see how well we can represent the information. Would you be able to set up an ODB site on the dev server for us? Also would you give Darrin view access to EVA wiki? Thanks.
> Greg
> - Proposed Volume 1 Data Format 
> - System
> - Subsystem/Assembly/Component
> - Physical Characteristics and Configuration
> - Performance Data 
> - Constraints
> - Limitations
> - Reference to applicable Tables and Figures

Also contact: Darrin Leleux

**Comment by darenwelsh** [comment]
ODB Wiki created. Greg and Darrin have admin rights and have begun testing it out.
