### ISSUE TITLE
On Meeting Minutes form, fix start time box

### ISSUE THREAD

**Issue by olsonjaredm** [FodWikis/FodWikis#5]
The 'start time' hours box displays as a huge screen-wide box instead of small like the 'start time' minutes box.

**Comment by marcd6** [comment]
For your field, you could try adding "input type=date". So it should look like this:

{{{field|Other Date|input type=date}}}

**Comment by jamesmontalvo3** [comment]
Looks like it's already using the date field type for the date. The time is screwy:

![image](https://cloud.githubusercontent.com/assets/716482/8989246/8bb5305c-36b0-11e5-9e3b-b22ff14303c9.png)

I added `input type=text` to both the time fields (even though only one was offending) and that solved the problem.

![image](https://cloud.githubusercontent.com/assets/716482/8989308/efab760c-36b0-11e5-8d2c-20d17acb28d3.png)

**Comment by olsonjaredm** [comment]
Thanks
