### ISSUE TITLE
Issue with Approved Revs and File namespace

### ISSUE THREAD

**Issue by jamesmontalvo3** [FodWikis/FodWikis#7]
From @emanspeaks: For approved revs I believe I should be able to approve things in the file namespace as well, but i don't see approve buttons anywhere.  I know on the extension page it says they should appear on the file version table instead of the page history like for articles, but I don't see the links in either place.  Am I missing something or is this a misconfig somewhere?

Issue imported from defunct TOPO Wiki repository

**Comment by jamesmontalvo3** [comment]
The version TOPO is running has Approved Revs configured at [[MediaWiki:Approvedrevs-permissions]]. In later versions this will be configured in LocalSettings.php, but for now it should be configured there.

To get file approvals working, either add settings to the "File" namespace or setup category approvals, and apply categories to the files you want to have approvals.

**Comment by emanspeaks** [comment]
Added "File" namespace to the config page and everything works now.

**Comment by jamesmontalvo3** [comment]
Awesome. Love seeing issues close.
